# remote_theme: JeffKoMS/mslearn-jekyll
exclude:
  - readme.md
  - .github/
header_pages:
  - index.html
author: Microsoft Learning
twitter_username: mslearning
github_username:  MicrosoftLearning
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
markdown: redcarpet
title: Lab Exercises
